// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FormIDEDemoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void formIDEDemo() {
    // Test name: FormIDEDemo
    // Step # | name | target | value
    // 1 | open | /webdriver2/ | 
    driver.get("https://www.edgewordstraining.co.uk/webdriver2/");
    // 2 | setWindowSize | 974x1040 | 
    driver.manage().window().setSize(new Dimension(974, 1040));
    // 3 | click | css=.last span | 
    driver.findElement(By.cssSelector(".last span")).click();
    // 4 | click | linkText=Forms | 
    driver.findElement(By.linkText("Forms")).click();
    // 5 | click | id=textInput | 
    driver.findElement(By.id("textInput")).click();
    // 6 | type | id=textInput | hello world
    driver.findElement(By.id("textInput")).sendKeys("hello world");
    // 7 | click | id=textArea | 
    driver.findElement(By.id("textArea")).click();
    // 8 | type | id=textArea | was here
    driver.findElement(By.id("textArea")).sendKeys("was here");
    // 9 | click | linkText=Submit | 
    driver.findElement(By.linkText("Submit")).click();
    // 10 | click | id=textInputValue | 
    driver.findElement(By.id("textInputValue")).click();
    // 11 | assertText | id=textInputValue | hello world
    assertThat(driver.findElement(By.id("textInputValue")).getText(), is("hello world"));
    // 12 | click | css=tr:nth-child(3) > td:nth-child(3) | 
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3)")).click();
    // 13 | verifyText | id=textAreaValue | was here
    assertThat(driver.findElement(By.id("textAreaValue")).getText(), is("was here"));
    // 14 | click | linkText=CSS/XPath | 
    driver.findElement(By.linkText("CSS/XPath")).click();
    // 15 | mouseDownAt | css=.ui-slider-handle | -41.71875,5.453125
    WebElement element = driver.findElement(By.cssSelector(".ui-slider-handle"));
    Actions builder = new Actions(driver);
    builder.moveToElement(element).clickAndHold().moveByOffset(100,0).release();
    builder.perform();
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    /**   {
      WebElement element = driver.findElement(By.cssSelector(".ui-slider-handle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 16 | mouseMoveAt | id=slider-holder | 212,24.5
    {
      WebElement element = driver.findElement(By.id("slider-holder"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 17 | mouseUpAt | id=slider-holder | 212,24.5
    {
      WebElement element = driver.findElement(By.id("slider-holder"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 18 | click | css=.ui-slider-handle |
    driver.findElement(By.cssSelector(".ui-slider-handle")).click();
    // 19 | click | linkText=Home |
    driver.findElement(By.linkText("Home")).click();*/
  }
}
